[project]
name = "sf-data-pipelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "polars>=1.24.0",
    "python-dotenv>=1.0.1",
    "tqdm>=4.67.1",
]
