CREATE TABLE IF NOT EXISTS assets(
    date DATE,
    barrid TEXT,
    cins TEXT,
    cusip TEXT,
    isin TEXT,
    localid TEXT,
    ticker TEXT,
    price DOUBLE,
    market_cap DOUBLE,
    price_source TEXT,
    currency TEXT,
    return DOUBLE,
    specific_return DOUBLE,
    yield DOUBLE,
    total_risk DOUBLE,
    specific_risk DOUBLE,
    historical_beta DOUBLE,
    predicted_beta DOUBLE,
    russell_2000 BOOLEAN,
    russell_1000 BOOLEAN,
    russell_3000_weight DOUBLE,
    russell_2000_weight DOUBLE,
    russell_1000_weight DOUBLE,
    PRIMARY KEY (date, barrid)
);